//
//  Previews.swift
//  TestDikidi
//
//  Created by sihtmark on 28.08.2023.
//

import Foundation

struct Previews {
    let previewResponseModel = TestDikidi.DataClass(
        title: "Онлайн-запись и бронирование услуг",
        image: "https://api-beauty.test.dikidi.ru/assets/images/beauty_app/first1.png",
        catalogCount: "11",
        blocks:
            TestDikidi.BlocksStruct(
                vip: [
                    TestDikidi.Favorite(id: "2216", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/33pr179bcr.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/33pr179bcr.jpg?size=f"), name: "Компания ОЗ", categories: ["Ногтевой сервис", "Ресницы", "Депиляция, эпиляция", "Визаж", "Татуаж, тату", "Усы, борода", "Барбершоп", "Анализы", "Танцы"]), TestDikidi.Favorite(id: "1908", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/52rjla23l4.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/52rjla23l4.jpg?size=f"), name: "VHS", categories: ["Единоборства"]),
                    TestDikidi.Favorite(id: "1684", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/44sa22891p.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/44sa22891p.jpg?size=f"), name: "Компашка Наташки", categories: []),
                    TestDikidi.Favorite(id: "1519", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v3/1bci1jlaeq.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v3/1bci1jlaeq.jpg?size=f"), name: "Ласт тест ооооооочень длиииииинное назваааааание, что не куда не поместиться", categories: ["Парикмахерские услуги", "Ногтевой сервис", "Ресницы", "Депиляция, эпиляция", "Брови", "Косметология, уход", "Визаж", "Массаж", "СПА", "Татуаж, тату", "Усы, борода", "Прочие", "Барбершоп", "Медицина", "Стоматология", "Анализы", "Фитнес", "Единоборства", "Йога", "Танцы", "Шиномонтаж", "Автосервис", "Автомойка", "Техосмотр", "Ветеринария", "Груминг", "Квест", "Сауна", "Ресторан", "Киберспорт", "Боулинг", "Автошкола", "Репетитор", "Курсы", "Языковая школа", "Фотостудия", "Аренда", "Коворкинг", "Клининг", "Психология"])
                ],
                shares: TestDikidi.Shares(list: [
                    TestDikidi.List(id: "1231", name: "Тест Акция 2", timeStart: "2022-11-13 20:13:20", timeStop: "2024-06-22 23:59:59", discountValue: "20", view: "95", usedCount: "12", companyID: "1684", icon: "https://f1.test.dikidi.ru/c1/v5/3uaqqbifhr.jpg", companyName: "Компашка Наташки", companyStreet: "Некрасова, 35", companyHouse: "Этаж 3, Сразу За Цветком и еще пройдите пожалуйста", companyImage: "https://f1.test.dikidi.ru/c1/v6/44sa22891p.jpg?size=q"),
                    TestDikidi.List(id: "1230", name: "Тесовая акция", timeStart: "2022-11-03 10:13:20", timeStop: "2024-09-13 23:59:59", discountValue: "20", view: "43", usedCount: "8", companyID: "1684", icon: "https://f1.test.dikidi.ru/c1/v5/7lp4n8a0ns.jpg", companyName: "Компашка Наташки", companyStreet: "Некрасова, 35", companyHouse: "Этаж 3, Сразу За Цветком и еще пройдите пожалуйста", companyImage: "https://f1.test.dikidi.ru/c1/v6/44sa22891p.jpg?size=q"),
                    TestDikidi.List(id: "1176", name: "Долгосрочная акция", timeStart: "2022-08-20 00:00:00", timeStop: "2025-08-27 23:59:59", discountValue: "1", view: "38", usedCount: "19", companyID: "1712", icon: "https://f1.test.dikidi.ru/c1/v4/51ufsefum6.jpg", companyName: "another \"test\"", companyStreet: "Центральный проезд Хорошевского Серебряного Бора", companyHouse: "657/24-Б.7", companyImage: "https://f1.test.dikidi.ru/c1/v5/2tj71e3vs4.jpg?size=q")
                ],
                                          count: "3"
                                         ),
                examples: "https://api-beauty.test.dikidi.ru/assets/images/beauty_app/examples/4.jpg",
                catalog: [
                    TestDikidi.Catalog(id: "2224", name: "Студия красоты", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/3n3abkbhcv.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/3n3abkbhcv.jpg?size=f"), street: "Vasileos Georgiou I", house: "", lat: "42.360082", lng: "-71.05888", categories: [], rating: 5.0, isMaster: false, currency: TestDikidi.Currency(id: "USD", title: "Доллар", abbr: "$")),
                    TestDikidi.Catalog(id: "2214", name: "ТИММЕЙД", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/m1e887k050.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/m1e887k050.jpg?size=f"), street: "Некрасова", house: "39", lat: "57.632158", lng: "39.873619", categories: [], rating: 5.0, isMaster: false, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "2147", name: "База НАТО", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/44f93algqu.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/44f93algqu.jpg?size=f"), street: "Баранова 6", house: "51", lat: "59.254769", lng: "54.733048", categories: [], rating: 4.0, isMaster: false, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "2145", name: "Тестовая компания фрилансера №1", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/2tosf29ksf.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/2tosf29ksf.jpg?size=f"), street: "Ленинская", house: "69", lat: "57.17886", lng: "39.392545", categories: [], rating: 0.0, isMaster: true, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "2144", name: "Тестовая компания №1", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v5/1rm5dhmok6.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v5/1rm5dhmok6.jpg?size=f"), street: "Московская", house: "", lat: "57.597193", lng: "39.857225", categories: [], rating: 3.6, isMaster: false, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "2143", name: "Чаёк, кофеёк", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v6/3g0to43lok.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v6/3g0to43lok.jpg?size=f"), street: "Где то тут", house: "88", lat: "57.626559", lng: "39.893813", categories: [], rating: 5.0, isMaster: false, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "1763", name: "Дмитрий Круглов", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v5/26gls5tl77.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v5/26gls5tl77.jpg?size=f"), street: "ростовская", house: "15", lat: "53.303828", lng: "34.309868", categories: [], rating: 0.0, isMaster: true, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "1762", name: "Моя компания", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v4/4skdkc9b8f.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v4/4skdkc9b8f.jpg?size=f"), street: "ростовская", house: "15", lat: "57.606236", lng: "39.866235", categories: [], rating: 0.0, isMaster: false, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "1432", name: "Автоплат РФ", image: TestDikidi.ImageStruct(thumb: "https://f1.test.dikidi.ru/c1/v3/196nat9vmg.jpg?size=m", origin: "https://f1.test.dikidi.ru/c1/v3/196nat9vmg.jpg?size=f"), street: "Некрасова, дом", house: "39Б", lat: "57.631571", lng: "39.873925", categories: [], rating: 0.0, isMaster: false, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб.")),
                    TestDikidi.Catalog(id: "799", name: "Рыбхоз &\"\'*Плотва\"*\'", image: TestDikidi.ImageStruct(thumb: "http://f1.test.dikidi.net/c1/v2/q1t7aciiac.jpg?size=m", origin: "http://f1.test.dikidi.net/c1/v2/q1t7aciiac.jpg?size=f"), street: "Михайловская 8", house: "apart 333", lat: "57.737807", lng: "39.758006", categories: [], rating: 0.0, isMaster: false, currency: TestDikidi.Currency(id: "RUB", title: "Российский рубль", abbr: "руб."))], examples2: "https://api-beauty.test.dikidi.ru/assets/images/beauty_app/examples2/1.png"), order: ["favorites", "categories", "vip", "shares", "popular", "certificates", "examples", "new", "banners", "catalog"]
    )
}
